Cloud Build Request - 2026-07-24 16:31:59

diff --git a/.github/workflows/crash-test.yml b/.github/workflows/crash-test.yml
--- a/.github/workflows/crash-test.yml
+++ b/.github/workflows/crash-test.yml
@@ -46,4 +46,14 @@ jobs:
         api-level: 31
         target: google_apis
         arch: x86_64
-        script: APK=$(find . -name "*.apk" | head -n 1); echo "Found APK: $APK"; adb install "$APK"; adb logcat -c; adb shell am start -n net.openvpn.openvpn/net.openvpn.openvpn.OpenVPNClient; sleep 10; echo "=========================================="; echo "🔥 CRASH / FATAL ERROR LOGS FROM EMULATOR 🔥"; echo "=========================================="; adb logcat -d *:E | grep -E "AndroidRuntime|FATAL|Exception|Caused by" || echo "No crash detected"
+        script: >
+          APK=$(find . -name "*.apk" | head -n 1);
+          echo "Found APK = $APK";
+          adb install "$APK";
+          adb logcat -c;
+          adb shell am start -n net.openvpn.openvpn/net.openvpn.openvpn.OpenVPNClient;
+          sleep 10;
+          echo "==========================================";
+          echo "CRASH / FATAL ERROR LOGS FROM EMULATOR";
+          echo "==========================================";
+          adb logcat -d *:E | grep -E "AndroidRuntime|FATAL|Exception|Caused by" || echo "No crash detected"
